added navbar to website
jkugsiya/TechnoIndiaNJR pull request #12
Opened 2021-05-29 10:50 UTC by sahuvivek2000

## Explanation

The PR includes Navbar.html which includes responsive navbar with logo
Fixes #bugnum:8

## Checklist

- [ x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: 8".)
- [ ] The PR explanation includes the words "Fixes #bugnum: 8" (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x ] The PR is made from a branch that's **not** called "master".
- [x ] The PR is made from a branch that is up-to-date with "master".
- [ x] The PR's branch is based on "master" and not on any other branch.

2021-05-29 11:09 UTC, jkugsiya requested changes
The desktop version of the website is fine but when switching to the mobile version the options disappear, that is expected behaviour though, but those options should be available in a hamburger menu instead.

2021-05-29 11:11 UTC, jkugsiya requested changes
Also, implement the list options when hovering some of the tabs as in the original website www.technonjr.org

2021-05-29 11:12 UTC, sahuvivek2000 commented
working on it

2021-05-29 11:14 UTC, jkugsiya requested changes
When we switch to the mobile version, the logo doesn't come up in the center it is slightly left from the center.

2021-05-29 11:18 UTC, jkugsiya requested changes
Also keep all the images under the images folder already made.

2021-05-29 12:56 UTC, jkugsiya commented
All the changes LGTM but follow this https://github.com/jkugsiya/TechnoIndiaNJR/pull/12#pullrequestreview-671736975 don't create a new image folder. The images folder is already present use that to keep all the images.

2021-05-29 12:57 UTC, jkugsiya commented
Also follow this: https://github.com/jkugsiya/TechnoIndiaNJR/pull/12#pullrequestreview-671736547

2021-05-29 13:04 UTC, sahuvivek2000 commented
there is no image folder

2021-05-29 13:52 UTC, jkugsiya commented
> there is no image folder

Fetch upstream and you will see there is one images folder in there
Follow [CONTRIBUTING.md](https://github.com/jkugsiya/TechnoIndiaNJR/blob/master/CONTRIBUTING.md) to see how to fetch and merge upstream

2021-05-29 14:31 UTC, jkugsiya commented on navbar.html
> +                <img src="./image/Techno-Logo_new.png" alt="" class="d-inline-block align-text-top">
```suggestion
                <img src="./images/Techno-Logo_new.png" alt="" class="d-inline-block align-text-top">
```

2021-05-30 04:42 UTC, jkugsiya commented
Thanks, @sahuvivek2000 LGTM. Approving changes and merging.

2021-05-30 04:42 UTC, merged