Fix #1 Added a responsive home page to the website with some designs
jkugsiya/TechnoIndiaNJR pull request #14
Opened 2021-05-30 06:51 UTC by m-ohit-s

## Explanation
This PR solves the #1 issue.
Added a home page to the existing index.html
Please check and suggest if any changes required.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR is made from a branch that's **not** called "master".
- [x] The PR is made from a branch that is up-to-date with "master".
- [x] The PR's branch is based on "master" and not on any other branch.

2021-05-30 07:09 UTC, jkugsiya commented on index.html
> +</head>
Carousel is not working because jquery and bootstrap js is not linked with the html

2021-05-30 07:10 UTC, jkugsiya commented on index.html
> +<section id="achievements" style="padding-top:10%;">
```suggestion
<section id="achievements">
```
use external css instead

2021-05-30 07:11 UTC, jkugsiya commented on index.html
> +        <div class="card mb-3" style="min-height:20px; box-shadow:10px 5px 10px #888888">
```suggestion
        <div class="card mb-3">
```
same- use external css

2021-05-30 07:20 UTC, jkugsiya requested changes
Left some changes to be done. Also look for all the same problem occurrences in the code and fix them.

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +        <div class="card mb-3" style="box-shadow:none;">
```suggestion
        <div class="card mb-3">
```
same

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +                <h4><a href="http://technonjr.org/news/techno-india-njr-is-participating-in-the-nvidia-gtc-conference-on-april-12th-2021/" title="Techno India NJR is participating in the NVIDIA GTC c
```suggestion
                <h4><a href="" title="Techno India NJR is participating in the NVIDIA GTC conference on April 12th, 2021.">Techno India NJR is participating in the NVIDIA GTC conference on April 12th, 2021.</a></h4>
```
Remove this link, we have to create our own instead

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +                <h4><a href="http://technonjr.org/news/placement-2020-21-cognizant-technologies-selects-3-techno-njr-students-at-a-package-of-5-41-lpa/" title="[PLACEMENT 2020-21] Cognizant Technolog
```suggestion
                <h4><a href="" title="[PLACEMENT 2020-21] Cognizant Technologies Selects 3 Techno NJR students at a Package of 5.41 LPA.">[PLACEMENT 2020-21] Cognizant Technologies Selects 3 Techno NJR students at a Package of 5.41 LPA.</a></h4>
```
Same

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +                <h4><a href="http://technonjr.org/news/thermax-selects-4-techno-njr-students/" title="Thermax selects 4 Techno NJR Students">Thermax selects 4 Techno NJR Students</a></h4>
```suggestion
                <h4><a href="">Thermax selects 4 Techno NJR Students</a></h4>
```
Same here

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +                <h4><a href="http://technonjr.org/news/startup-venture-wricks-by-ex-students-of-techno-india-njr-incubated-at-techno-india-njr-incubation-center-has-won-the-second-prize-of-canadian-1
```suggestion
                <h4><a href="" title="Startup Venture Wricks by ex-students of Techno India NJR incubated at Techno India NJR Incubation Center has won the second prize of Canadian $12500/-">Startup Venture Wricks by ex-students of Techno India NJR incubated at Techno India NJR Incubation Center has won the second prize of Canadian $12500/-</a></h4>
```
Same

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +    </div>
```suggestion
      <a href="" class="btn btn-lg btn-secondary">READ MORE</a>
    </div>
```
Don't use this links of external website. We have to create our own pages later instead.

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +        </div>
```suggestion
            <img src="" class="card-image-top" alt="International Research">
        </div>
```
Download and keep the image in images folder instead using them from external website

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +      </div>
```suggestion
        <a href="">READ MORE</a>
      </div>
```
Remove link to external website

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +          <div class="image__overlay image__overlay--blur">
```suggestion
          <img class="details card-image-top" src="" alt="Computer Science Engineering &#038; Information Technology (CSE &#038; IT)">
          <div class="image__overlay image__overlay--blur">
```
Download and use local image here

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +                Computer Science Engineering &#038; Information Technology (CSE &#038; IT)
```suggestion
              <a title="Computer Science Engineering &#038; Information Technology (CSE &#038; IT)" href="">
                Computer Science Engineering &#038; Information Technology (CSE &#038; IT)
```
Remove links to the external website

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +                Computer Science Engineering &#038; Information Technology (CSE &#038; IT)
```suggestion
              <a title="Computer Science Engineering &#038; Information Technology (CSE &#038; IT)" href="">
                Computer Science Engineering &#038; Information Technology (CSE &#038; IT)
```
Same

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +          <div class="image__overlay image__overlay--blur">
```suggestion
          <img src="" class="details card-image-top" alt="Electronics and Communication Engineering (ECE)">
          <div class="image__overlay image__overlay--blur">
```
Download the image

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +              <a title="Electronics and Communication Engineering (ECE)" href="http://technonjr.org/department/electronics-and-communication-engineering-ece/ ">
```suggestion
              <a title="Electronics and Communication Engineering (ECE)" href=" ">
```
Download and use images

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +              <a title="Electronics and Communication Engineering (ECE)" href="http://technonjr.org/department/electronics-and-communication-engineering-ece/ ">
```suggestion
              <a title="Electronics and Communication Engineering (ECE)" href="">
```
Remove link to external website

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +          <div class="image__overlay image__overlay--blur">
```suggestion
          <img src="">
          <div class="image__overlay image__overlay--blur">
```
Download image

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +                Mechanical Engineering (ME)
```suggestion
              <a title="Mechanical Engineering (ME)" href=" ">
                Mechanical Engineering (ME)
```
Don't use link to external website

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +                Mechanical Engineering (ME)
```suggestion
              <a title="Mechanical Engineering (ME)" href="">
                Mechanical Engineering (ME)
```
Same

2021-05-30 07:20 UTC, jkugsiya commented on index.html
> +          <img src="http://technonjr.org/wp-content/uploads/2014/10/electronics-550x400.jpg" class="details card-image-top" alt="Electrical Engineering (EE)">
```suggestion
          <img src="">
```
Same

2021-05-30 07:50 UTC, m-ohit-s commented on index.html
> +                <h4><a href="http://technonjr.org/news/startup-venture-wricks-by-ex-students-of-techno-india-njr-incubated-at-techno-india-njr-incubation-center-has-won-the-second-prize-of-canadian-1
Should i leave the links empty for now

2021-05-30 08:05 UTC, m-ohit-s commented
Should I Leave the links empty for now

2021-05-30 10:32 UTC, jkugsiya commented
> Should I Leave the links empty for now

Yes you can leave the links empty

2021-05-30 16:02 UTC, jkugsiya requested changes
PTAL @m-ohit-s. Left some comments and changes to be done.

2021-05-30 16:02 UTC, jkugsiya commented on index.html
> +      </div>
These buttons and heading don't look good on small screen sizes:
![image](https://user-images.githubusercontent.com/42642325/120111139-5f1a2d80-c18e-11eb-9367-26a0f0c89a62.png)

2021-05-31 03:29 UTC, jkugsiya commented
Your PR needs to update with the upstream master and also include the footer now as it is available.

2021-05-31 05:54 UTC, jkugsiya approved these changes
LGMT, @m-ohit-s! Approving changes

2021-05-31 05:54 UTC, merged