Fix Part of #4: Created `Mechanical Department` Page
jkugsiya/TechnoIndiaNJR pull request #29
Opened 2021-06-01 04:30 UTC by jeakansh

## Explanation

Fixes Part of #4 : Created `Mechanical Department` Page which is a part of Department Page.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR is made from a branch that's **not** called "master".
- [x] The PR is made from a branch that is up-to-date with "master".
- [x] The PR's branch is based on "master" and not on any other branch.

2021-06-01 09:30 UTC, jkugsiya requested changes
as you can see below image that the content is not properly responsive (the navbar-menu icon is hidden and some text is getting hidden) and the user needs to swipe the screen in order to see the full content, that is not the expected behaviour.
![image](https://user-images.githubusercontent.com/42642325/120300660-c5679300-c2e9-11eb-9328-67141fef4c2f.png)

2021-06-01 15:09 UTC, jeakansh commented
![Responsive](https://user-images.githubusercontent.com/45876724/120346816-5a35b500-c319-11eb-8efa-11f5e50df904.PNG)
The nav-bar and the complete content is Responsive.

2021-06-02 04:46 UTC, jkugsiya requested changes
developer options - iPad orientation portrait. Look at the navbar and also the information cards they are going out of screen bounds and hiding the written content in it:

![image](https://user-images.githubusercontent.com/42642325/120425094-3ca13380-c38b-11eb-9471-f31bae2e71b8.png)

Also why this blur affect on the footer:

![image](https://user-images.githubusercontent.com/42642325/120425233-78d49400-c38b-11eb-988b-02147763a5ef.png)

2021-06-02 07:45 UTC, jkugsiya commented on mechanical_Department.html
> +                <div class= "card col-lg-3 col-md-4 col-10 col-sm-3 mech-faculty-card card-no-shadow" >
This one is col-md-4 and others are col-md-3. Make this too col-md-3

2021-06-02 07:46 UTC, jkugsiya commented on mechanical_Department.html
> +                <div class= "card col-lg-3 col-md-4 col-10 col-sm-3 mech-faculty-card card-no-shadow" >
Also use col-sm-4 everywhere in the faculty images card

2021-06-02 07:55 UTC, jeakansh commented on mechanical_Department.html
> +                <div class= "card col-lg-3 col-md-4 col-10 col-sm-3 mech-faculty-card card-no-shadow" >
I have done all the required Changes.

2021-06-02 07:58 UTC, jkugsiya approved these changes
LGTM, Thanks! @jeakansh

2021-06-02 07:58 UTC, merged